services:
  application:
    volumes:
      - static_volume:/staticfiles
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/staticfiles
    ports:
      - "80:80"
volumes:
  static_volume:
