# Generated by Django 5.0.6 on 2024-07-18 14:32

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cycling',
            name='start_less_than_or_equal_now',
        ),
        migrations.RemoveConstraint(
            model_name='jogging',
            name='start_less_than_or_equal_now',
        ),
        migrations.RemoveConstraint(
            model_name='powertraining',
            name='start_less_than_or_equal_now',
        ),
        migrations.RemoveConstraint(
            model_name='swimming',
            name='start_less_than_or_equal_now',
        ),
        migrations.RemoveConstraint(
            model_name='walking',
            name='start_less_than_or_equal_now',
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cycling',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.functions.datetime.Now())), name='start_less_than_or_equal_now'),
        ),
        migrations.AddConstraint(
            model_name='jogging',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.functions.datetime.Now())), name='start_less_than_or_equal_now'),
        ),
        migrations.AddConstraint(
            model_name='powertraining',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.functions.datetime.Now())), name='start_less_than_or_equal_now'),
        ),
        migrations.AddConstraint(
            model_name='swimming',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.functions.datetime.Now())), name='start_less_than_or_equal_now'),
        ),
        migrations.AddConstraint(
            model_name='walking',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.functions.datetime.Now())), name='start_less_than_or_equal_now'),
        ),
    ]
