# Generated by Django 5.0.6 on 2024-07-17 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cycling',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', datetime.datetime(2024, 7, 17, 10, 31, 52, 876702))), name='start_less_than_now'),
        ),
        migrations.AddConstraint(
            model_name='jogging',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', datetime.datetime(2024, 7, 17, 10, 31, 52, 876702))), name='start_less_than_now'),
        ),
        migrations.AddConstraint(
            model_name='powertraining',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', datetime.datetime(2024, 7, 17, 10, 31, 52, 876702))), name='start_less_than_now'),
        ),
        migrations.AddConstraint(
            model_name='swimming',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', datetime.datetime(2024, 7, 17, 10, 31, 52, 876702))), name='start_less_than_now'),
        ),
        migrations.AddConstraint(
            model_name='walking',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', datetime.datetime(2024, 7, 17, 10, 31, 52, 876702))), name='start_less_than_now'),
        ),
    ]
