# Generated by Django 5.0.6 on 2024-07-11 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cyclingtraining',
            name='start_date_grater_than_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='jogging',
            name='start_date_grater_than_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='powertraining',
            name='start_date_grater_than_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='swimmingtraining',
            name='start_date_grater_than_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='walk',
            name='start_date_grater_than_end_date',
        ),
        migrations.AlterField(
            model_name='approach',
            name='repeats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='approach',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cyclingtraining',
            name='climb',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='carbohydrates',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fats',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='dishcount',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
