# Generated by Django 5.0.6 on 2024-07-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycling',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='jogging',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='powertraining',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='swimming',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='walking',
            options={'ordering': ['-start']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='owner',
            new_name='user',
        ),
    ]
