# Generated by Django 5.0.6 on 2024-07-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_walk_joggingtraining_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CyclingTraining',
            new_name='Cycling',
        ),
        migrations.RenameModel(
            old_name='SwimmingTraining',
            new_name='Jogging',
        ),
        migrations.RenameModel(
            old_name='WalkTraining',
            new_name='Swimming',
        ),
        migrations.RenameModel(
            old_name='JoggingTraining',
            new_name='Walking',
        ),
    ]
