# Generated by Django 5.0.6 on 2024-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_dish_name_for_user'),
        ),
    ]
