# Generated by Django 5.0.6 on 2024-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_category_foodcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclingtraining',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cyclingtraining',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jogging',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jogging',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='powertraining',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='powertraining',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='swimmingtraining',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='swimmingtraining',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walk',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walk',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
