# Generated by Django 5.0.6 on 2024-07-08 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cyclingtraining_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclingtraining',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jogging',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='powertraining',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='powertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swimmingtraining',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
