# Generated by Django 5.0.6 on 2024-07-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cyclingtraining_end_alter_jogging_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='date',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='exercise',
        ),
        migrations.AddField(
            model_name='approach',
            name='repeats',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PowerTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approaches', models.ManyToManyField(to='main.approach')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
            ],
        ),
    ]
