# Generated by Django 5.0.6 on 2024-07-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_approach_date_remove_approach_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powertraining',
            name='approaches',
            field=models.ManyToManyField(to='main.powertrainingexercise'),
        ),
    ]
