# Generated by Django 5.0.6 on 2024-07-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_powertraining_approaches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powertraining',
            old_name='approaches',
            new_name='exercises',
        ),
    ]
