# Generated by Django 5.0.6 on 2024-07-08 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_approaches_powertraining_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powertraining',
            name='exercises',
        ),
        migrations.AddField(
            model_name='powertrainingexercise',
            name='power_training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.powertraining'),
        ),
        migrations.AlterField(
            model_name='powertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
